title = "CORE"
baseURL = "https://core-rocket.github.io/website"
languageCode = "ja-jp"
theme = "universal"
publishDir = "docs"

MetaDataFormat = "yaml"
DefaultContentLanguage = "ja"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

# define the number of posts per page
pagenate = 10

[menu]
[[menu.main]]
	identifier = "home"
	name = "Home"
	url = "/"
	weight = 1

[[menu.main]]
	identifier = "blog"
	name = "Blog"
	url = "/blog/"
	weight = 2

# main menu

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
	email = "core.rockets@gmail.com"
	contact_form_ajax = false

	about_us = "Challengers Of Rocket Engineering"
	copyright= "Copyright (c) 2020, Challengers Of Rocket Engineering; all rights reserved."

	date_format = "2006/1/2 15:04:05"


  favicon = ""
  description = ""
  facebook = ""
  twitter = "https://twitter.com/CORE_Rocket"
  instagram = ""
  youtube = ""
  github = "https://github.com/core-rocket"
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 2

[Permalinks]
	blog = "/blog/:year/:month/:day/:filename/"

[params.topbar]
	enable = false

[params.widgets]
	categories = true
	tags = true
	search = true

[params.carousel]
    enable = false

[params.features]
    enable = false

[params.testimonials]
    enable = false

[params.see_more]
    enable = false

[params.clients]
    enable = false

[params.recent_posts]
    enable = true
    title = "From our blog"
    subtitle = "test subtitle"
