title = "CORE"
baseURL = "https://core-rocket.github.io/website"
languageCode = "ja-jp"
theme = "universal"
publishDir = "docs"

MetaDataFormat = "yaml"
DefaultContentLanguage = "ja"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

# define the number of posts per page
pagenate = 10

[menu]
[[menu.main]]
	identifier = "home"
	name = "Home"
	url = "/"
	weight = 1

[[menu.topbar]]
	weight = 1
	name = "Twitter"
	url = "https://twitter.com/CORE_Rocket"
	pre = "<i class='fab fa-2x fa-twitter'></i>"

[[menu.topbar]]
	weight =  2
	name = "GitHub"
	url = "https://github.com/core-rocket"
	pre = "<i class='fab fa-2x fa-github'></i>"

# main menu

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
	# social media
	twitter_site = "CORE_Rocket"
	default_sharing_image = "img/logo-white.png"

	# style
	style = "red"

	email = "core.rockets@gmail.com"
	contact_form_ajax = false

	about_us = "Challengers Of Rocket Engineering"
	copyright= "Copyright (c) 2020, Challengers Of Rocket Engineering; all rights reserved."

	date_format = "2006/1/2 15:04:05"

	logo = "img/logo-white-50x50.png"
	logo_small = "img/logo-white-50x50.png"

[Permalinks]
	blog = "/blog/:year/:month/:day/:filename/"

[params.topbar]
	enable = true
	text = ""

[params.widgets]
	categories = true
	tags = true
	search = true

[params.carousel]
    enable = false

[params.features]
    enable = false

[params.testimonials]
    enable = false

[params.see_more]
    enable = false

[params.clients]
    enable = false

[params.recent_posts]
    enable = true
    title = "最近の投稿"
    subtitle = "test subtitle"
